# Generated by Django 5.0.3 on 2024-03-28 09:31

import MenTEL_website_softuni_django_exam.profiles.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(error_messages={'min_length': 'Username must be at least 3 chars long!'}, max_length=15, validators=[django.core.validators.MinLengthValidator(3), MenTEL_website_softuni_django_exam.profiles.validators.username_letter_validator])),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField(help_text='Age requirement: 21 years and above.', validators=[django.core.validators.MinValueValidator(18)])),
                ('password', models.CharField(max_length=15)),
                ('first_name', models.CharField(blank=True, max_length=25, null=True)),
                ('last_name', models.CharField(blank=True, max_length=25, null=True)),
                ('profile_picture', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
